name: better_steam_achievements
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2  
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  go_router: ^14.2.3
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "Images/icon.png"
    icon_size: 256